name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 替换 Gordon79 为你的 HF 用户名，CoolDown_Stock 为你的 Space 名字
          git push -f https://Gordon79:$HF_TOKEN@huggingface.co/spaces/Gordon79/CoolDown_Stock main
